from typing import Annotated, List, Dict, Any, Optional
from pydantic import BaseModel
from typing_extensions import TypedDict


def merge_str_lists(
    left: Optional[List[Any]], right: Optional[List[Any]]
) -> List[Any]:
    """Union-append reducer for memory-id lists from parallel writes."""
    merged: List[Any] = list(left or [])
    for item in right or []:
        if item not in merged:
            merged.append(item)
    return merged


class SubtaskResult(BaseModel):
    subtask_id: str
    content: str
    status: str = "success"  # success, error, escalate
    error: Optional[str] = None
    retry_count: int = 0
    confidence: float = 1.0


def merge_dicts(left: Optional[Dict[str, Any]], right: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Reducer that merges partial dict updates from parallel branches.

    ``operator.add`` cannot be used on dict channels (dict + dict raises
    TypeError), which previously made every graph run crash on the first
    state update coming out of a parallel ``Send`` branch.
    """
    merged: Dict[str, Any] = dict(left or {})
    merged.update(right or {})
    return merged


class GraphState(TypedDict, total=False):
    # Input task
    task_id: str
    user_id: str
    task_description: str

    # The plan generated by the supervisor, and how sure it was
    plan: Optional[List[Dict[str, Any]]]
    plan_confidence: float
    # Memory ids the plan leaned on, recorded to spans and run_metadata.
    memory_ids_used: Annotated[List[int], merge_str_lists]

    # Accumulators: dict channels need an explicit merge reducer so that
    # parallel branches can write without clobbering each other.
    results: Annotated[Dict[str, SubtaskResult], merge_dicts]
    attempts: Annotated[Dict[str, int], merge_dicts]
    review_feedback: Annotated[Dict[str, str], merge_dicts]
    # Signature -> approval info for sensitive tool calls and failed subtasks.
    pending_approvals: Annotated[Dict[str, Any], merge_dicts]
    failure_decisions: Annotated[Dict[str, str], merge_dicts]
    human_takeover: bool

    # Final synthesized response
    final_response: Optional[str]

    # Context for specialists
    shared_context: str
