from typing import Annotated, List, Dict, Any, Optional
from pydantic import BaseModel, Field
from typing_extensions import TypedDict
import operator

class SubtaskResult(BaseModel):
    subtask_id: str
    content: str
    status: str = "success" # success, error, escalate
    error: Optional[str] = None
    retry_count: int = 0
    confidence: float = 1.0

class GraphState(TypedDict):
    # Input task
    task_description: str
    
    # The plan generated by the supervisor
    plan: Optional[List[Dict[str, Any]]] 
    
    # Accumulator for results: subtask_id -> result
    # Using operator.add allows LangGraph to merge results from parallel branches
    results: Annotated[Dict[str, SubtaskResult], operator.add]
    
    # Final synthesized response
    final_response: Optional[str]
    
    # Context for specialists
    shared_context: str
